### PR TITLE
Add hypothetical detectors in the ymir json template.

### PR DESCRIPTION
**Pull request by YooSunYoung**
For testing event data assembling.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Why can't we use Loki template? This is what we want to use for demoing data reduction anyway.

**Comment by YooSunYoung** [comment]
> Why can't we use Loki template? This is what we want to use for demoing data reduction anyway.

Loki template is too large... I guess I can just prune them though. Should I...?

**Comment by SimonHeybrock** [comment]
Too large for what? The size is something we have to be able to deal with, and since we want to start working on Loki workflow with Beamlime very soon it cannot be postponed long.

**Comment by YooSunYoung** [comment]
> Too large for what? The size is something we have to be able to deal with, and since we want to start working on Loki workflow with Beamlime very soon it cannot be postponed long.

For putting somewhere accessible and download it, etc to use it for unit tests.
I already tested it with loki json file as well.

**Review by SimonHeybrock — APPROVED** [review]

**Pull request merged**
